[agent]
  interval = "1s"
  round_interval = true
  flush_interval = "500ms"
  omit_hostname = true
  debug = true
  quiet = false

########################
# MQTT → OPCUA METRICS
########################
[[inputs.mqtt_consumer]]
  servers   = ["tcp://emqx:1883"]
  topics    = ["plant/#"]
  topic_tag = "mqtt_topic"
  client_id = "telegraf-opcua"
  qos       = 1
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "opcua"

    # timestamp from OPCUA
    timestamp_path   = "ts"
    timestamp_format = "rfc3339"

    # ===== FIELD =====
    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "value_num"
      rename = "value"

    # ===== TAGS =====
    [[inputs.mqtt_consumer.json_v2.tag]]
      path   = "nodeid"
      rename = "nodeid"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path   = "tag"
      rename = "opcua_tag"


########################
# OUTPUT → INFLUXDB v2
########################
[[outputs.influxdb_v2]]
  urls         = ["${INFLUX_URL}"]
  token        = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket       = "${INFLUX_BUCKET}"

########################
# DEBUG OUTPUT
########################
[[outputs.file]]
  files = ["stdout"]

########################
# SYSTEM METRICS
########################
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs","devtmpfs","overlay","aufs","squashfs"]

[[inputs.diskio]]

[[inputs.system]]
